--System Privileges
CREATE USER ZEYNEP IDENTIFIED BY ZEYNEP 
GRANT CREATE SESSION TO ZEYNEP;
GRANT CONNECT,RESOURCE TO ZEYNEP;

CREATE USER BILGE IDENTIFIED BY BILGE;
GRANT CREATE SESSION TO BILGE;
GRANT CONNECT,RESOURCE TO BILGE;

GRANT CREATE ROLE TO NAZLI;
