SELECT *FROM  NAZLI.DEPARTMENTS;

INSERT INTO NAZLI.DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID) VALUES (50,'COUNTERS',1100);

DELETE FROM NAZLI.DEPARTMENTS WHERE DEPARTMENT_ID=50;

COMMIT;

SET ROLE R_INSDEL;

INSERT INTO NAZLI.DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID) VALUES (50,'COUNTER',1100);