/*
CREATE:
-->Database
-->User
-->Table
-->View
-->(Data)Type
-->Package(PL/SQL)
-->Procedure(PL/SQL)
-->Function(PL/SQL)
-->Trigger(PL/SQL)
*/

CREATE  TABLE REGIONS(
REGION_ID NUMBER,
REGION_NAME VARCHAR(25)
);

CREATE TABLE COUNTRIES(
COUNTRY_ID CHAR(2),
COUNTRY_NAME VARCHAR2(40),
REGION_ID NUMBER
);

CREATE TABLE LOCATIONS(
LOCATION_ID NUMBER(4),
STREET_ADRESS VARCHAR(40),
POSTAL_CODE VARCHAR(12),
CITY VARCHAR2(30) NOT NULL,
STATE_PROVINCE VARCHAR2(25),
COUNTRY_ID CHAR(2)
);

DROP TABLE LOCATIONS

CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID NUMBER(2),
DEPARTMENT_NAME VARCHAR2(30),
MANAGER_ID NUMBER(6),
LOCATION_ID NUMBER(4)
);

DROP TABLE DEPARTMENTS--TABLOYU TAMAMEN SİLMEK İÇİN KULLANIDLIR

CREATE TABLE JOBS(
JOB_ID VARCHAR2(10),
JOB_TITLE VARCHAR2(35) NOT NULL,
MIN_SALARY NUMBER(6),
MAX_SALARY NUMBER(6)
);

CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER(6),
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(25),
EMAIL VARCHAR2(25) NOT NULL,
PHONE_NUMBER VARCHAR(20),
HIRE_DATE DATE NOT NULL,
JOB_ID VARCHAR2(10),
SALARY NUMBER(8,2),
COMISSON_PCT NUMBER(2,2),
MANAGER_ID NUMBER(6),
CONSTRAINT emp_salary_mın CHECK(salary>0),
CONSTRAINT emp_email_uk UNIQUE (EMAIL),
DEPARTMENT_ID NUMBER(2)
);

DROP TABLE EMPLOYEES

CREATE TABLE JOB_HISTORY (
EMPLOYEE_ID NUMBER(6),
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
JOB_ID VARCHAR2(10),
DEPARTMENT_ID NUMBER(4),
CONSTRAINT jhist_date_interval CHECK (END_DATE >START_DATE )
);
