SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'REGIONS';
/*Tablonun özelliklerini bulmak için diyorum*/

INSERT INTO REGIONS VALUES(1,'Europe');
ALTER TABLE REGIONS ADD POPULATE NUMBER(15);
INSERT INTO REGIONS VALUES  (2,'Asia');--3 tane sütun olduğu için,hangi sütunları kullanacağımız yazılmalı.
INSERT INTO REGIONS (REGION_ID,REGION_NAME) VALUES (2,'Asia');
ALTER TABLE REGIONS DROP COLUMN POPULATE;
SELECT *FROM REGIONS 

SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'COUNTRIES';

SELECT *FROM REGIONS

INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID) VALUES ('TR','Türkiye',1);
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID) VALUES ('KT','KKTC',1);
INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID) VALUES ('IT','Italy',1);

SELECT *FROM COUNTRIES c 


DELETE FROM COUNTRIES 
DELETE FROM REGIONS 

--------------------------------
-- REGIONS
--------------------------------

INSERT INTO REGIONS VALUES (1,'Europe');
INSERT INTO REGIONS VALUES (2,'Americas');
INSERT INTO REGIONS VALUES (3,'Asia');
INSERT INTO REGIONS VALUES (4,'Middle East and Africa');

--------------------------------
-- COUNTRIES
--------------------------------

INSERT INTO COUNTRIES VALUES ('TR','Turkey',1);
INSERT INTO COUNTRIES VALUES ('DE','Germany',1);
INSERT INTO COUNTRIES VALUES ('US','United States',2);
INSERT INTO COUNTRIES VALUES ('BR','Brazil',2);
INSERT INTO COUNTRIES VALUES ('CN','China',3);
INSERT INTO COUNTRIES VALUES ('JP','Japan',3);

--------------------------------
-- LOCATIONS
--------------------------------

INSERT INTO LOCATIONS VALUES (1000,'Ataturk Cad. 10','34000','Istanbul','Marmara','TR');
INSERT INTO LOCATIONS VALUES (1100,'Berlin Street 22','10115','Berlin','Berlin','DE');
INSERT INTO LOCATIONS VALUES (1200,'5th Avenue','10001','New York','NY','US');
INSERT INTO LOCATIONS VALUES (1300,'Tokyo Center','150000','Tokyo','Tokyo','JP');

--------------------------------
-- JOBS
--------------------------------

INSERT INTO JOBS VALUES ('AD_PRES','President',20000,40000);
INSERT INTO JOBS VALUES ('IT_PROG','Programmer',4000,10000);
INSERT INTO JOBS VALUES ('HR_REP','HR Representative',3000,8000);
INSERT INTO JOBS VALUES ('SA_MAN','Sales Manager',8000,15000);

--------------------------------
-- DEPARTMENTS
--------------------------------

INSERT INTO DEPARTMENTS VALUES (10,'Administration',NULL,1000);
INSERT INTO DEPARTMENTS VALUES (20,'IT',NULL,1200);
INSERT INTO DEPARTMENTS VALUES (30,'Human Resources',NULL,1100);
INSERT INTO DEPARTMENTS VALUES (40,'Sales',NULL,1300);

--------------------------------
-- EMPLOYEES
--------------------------------

INSERT INTO EMPLOYEES VALUES
(100,'Steven','King','SKING','515123456',
TO_DATE('2003-06-17','YYYY-MM-DD'),
'AD_PRES',24000,NULL,NULL,10);

INSERT INTO EMPLOYEES VALUES
(101,'Neena','Kochhar','NKOCHHAR','515123457',
TO_DATE('2005-09-21','YYYY-MM-DD'),
'IT_PROG',9000,NULL,100,20);

INSERT INTO EMPLOYEES VALUES
(102,'Lex','De Haan','LDEHAAN','515123458',
TO_DATE('2001-01-13','YYYY-MM-DD'),
'HR_REP',6000,NULL,100,30);

INSERT INTO EMPLOYEES VALUES
(103,'Alexander','Hunold','AHUNOLD','515123459',
TO_DATE('2006-01-03','YYYY-MM-DD'),
'IT_PROG',8000,NULL,101,20);

INSERT INTO EMPLOYEES VALUES
(104,'Bruce','Ernst','BERNST','515123460',
TO_DATE('2007-05-21','YYYY-MM-DD'),
'SA_MAN',12000,NULL,100,40);

--------------------------------
-- JOB HISTORY
--------------------------------

INSERT INTO JOB_HISTORY VALUES
(102,
TO_DATE('1998-01-01','YYYY-MM-DD'),
TO_DATE('2000-12-31','YYYY-MM-DD'),
'IT_PROG',
20);

INSERT INTO JOB_HISTORY VALUES
(101,
TO_DATE('2002-02-01','YYYY-MM-DD'),
TO_DATE('2005-09-20','YYYY-MM-DD'),
'HR_REP',
30);

/*İnsert işlemi yaparken önce parent sonra child,delete yaparken önce childe sonra parent ilişkisi korunur.*/


SELECT *FROM EMPLOYEES e 
SELECT MANAGER_ID,FIRST_NAME,LAST_NAME,EMAIL FROM EMPLOYEES;
SELECT MANAGER_ID AS MGR,FIRST_NAME ADI,LAST_NAME SOYISMI,EMAIL EPOSTA FROM EMPLOYEES e 
SELECT MANAGER_ID "MUDUR NO",FIRST_NAME "ILK ADI",LAST_NAME "AİLE İSMİ",EMAIL "E POSTA" FROM EMPLOYEES 

SELECT *FROM EMPLOYEES e WHERE e.DEPARTMENT_ID =40;
SELECT *FROM EMPLOYEES e WHERE e.DEPARTMENT_ID IN (10,20);
SELECT *FROM EMPLOYEES e WHERE e.DEPARTMENT_ID =10 OR  e.DEPARTMENT_ID =20

SELECT *FROM EMPLOYEES e WHERE e.LAST_NAME  LIKE 'K%'
SELECT *FROM EMPLOYEES  e WHERE e.LAST_NAME LIKE '%oc%'


--Soy isminin 2.karakteri r 4.karekteri s olan adaylar
SELECT *FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '_r_s%';
SELECT *FROM EMPLOYEES e WHERE e.SALARY>9000 AND e.COMISSON_PCT IS NULL;

SELECT *FROM EMPLOYEES e ORDER BY DEPARTMENT_ID DESC,SALARY ASC,JOB_ID ;
/*Soldan sağa doğru bir sıralama yapar eğer department_ıd aynı ise salary baz alınır.Hem department_ıd hem de salary aynı ise job_ıd baz alınır.*/

SELECT MANAGER_ID,FIRST_NAME,LAST_NAME,EMAIL FROM EMPLOYEES
--ORDER BY MANAGER_ID;
ORDER BY 1--Manager_ıd ye göre sıralar























