SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID,DEPARTMENT_ID  FROM EMPLOYEES e 


--1
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID 
FROM EMPLOYEES e 
START WITH MANAGER_ID IS NULL -- En üstteki kişiden (Steven King) başla
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;


--2
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID,LEVEL
FROM EMPLOYEES e 
START WITH MANAGER_ID IS NULL -- En üstteki kişiden (Steven King) başla
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

--3
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID,LEVEL
FROM EMPLOYEES e 
START WITH EMPLOYEE_ID=101 -- En üstteki kişiden (Steven King) başla
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
ORDER SIBLINGS BY LAST_NAME;
--SIBLINGS:HİYERARŞİK SORGULAMAYI GÖZETEREK SIRALAR

SELECT LAST_NAME,CONNECT_BY_ROOT LAST_NAME,
LEVEL -1,SYS_CONNECT_BY_PATH(LAST_NAME,'/')
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID=20
CONNECT BY PRIOR EMPLOYEE_ID=MANAGER_ID

