CREATE TABLE EMPLOYEES_COPY AS 
SELECT * FROM EMPLOYEES;

SELECT *FROM EMPLOYEES_COPY

UPDATE EMPLOYEES_COPY SET
SALARY = SALARY * 1.20,
COMISSON_PCT = 0.25
WHERE EMPLOYEE_ID <> 100;

SELECT SALARY,COMISSON_PCT FROM EMPLOYEES_COPY

COMMIT;

SELECT SALARY,COMISSON_PCT FROM EMPLOYEES_COPY WHERE EMPLOYEE_ID IN (101,102);
UPDATE EMPLOYEES_COPY SET 
SALARY=SALARY-400,
COMISSON_PCT=NULL
WHERE EMPLOYEE_ID IN (101,102);

ROLLBACK --işlemleri geri almak için kullanılır.

SELECT EMPLOYEE_ID,SALARY,COMISSON_PCT FROM EMPLOYEES_COPY
WHERE DEPARTMENT_ID=10

UPDATE EMPLOYEES_COPY A SET 
A.SALARY =(SELECT B.SALARY FROM EMPLOYEES B
WHERE A.EMPLOYEE_ID=B.EMPLOYEE_ID)

COMMIT 

SELECT EMPLOYEE_ID,SALARY,COMISSON_PCT FROM 
EMPLOYEES_COPY WHERE DEPARTMENT_ID=10


--SHOW USER; HANGİ KULLANICIYLA BAĞLANDIĞIMIZI ÖĞRENMEK İÇİN KULLANILIR

DELETE FROM EMPLOYEES_COPY

SELECT *FROM EMPLOYEES_COPY 

DROP TABLE EMPLOYEES_COPY



